dist: xenial
sudo: required
services:
  - docker
jobs:
  include:
    - stage: build/push docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd ${TRAVIS_BUILD_DIR}/dockerfiles
        - make docker_pull_cpu
        - travis_wait 50 make docker_build_cpu
        - travis_retry make docker_push_cpu
    - stage: build/push docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd ${TRAVIS_BUILD_DIR}/dockerfiles
        - make docker_pull_cpu
        - travis_wait 50 make docker_build_gpu
        - travis_retry 50 make docker_push_gpu
    - stage: update microbadger
      script: 'curl -X POST https://github.com/rai-project/go-'
