jobs:
  - job: CPU
    timeoutInMinutes: 0
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_pull_cpu
          make docker_build_cpu
          ./push_cpu.sh
  - job: GPU
    timeoutInMinutes: 0
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles
          make docker_pull_gpu
          make docker_build_gpu
          ./push_gpu.sh
  - job: Update_Microbadger
    dependsOn:
      - CPU
      - GPU
    steps:
      - script: 'curl -X POST https://hooks.microbadger.com/images/carml/go-mxnet/1MrtzLGOTLhD_lTAZ2Ksy0HP-nI='
